# Bag-of-words

In [2]:
%run -i "../util/util_simple_classifier.ipynb"
from sklearn.feature_extraction.text import CountVectorizer
import sys

c:\Users\ravik\anaconda3\envs\nlp_cookbook\lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


In [3]:
(train_df, test_df) = load_train_test_dataset_pd()

In [8]:
vectorizer = CountVectorizer(max_df=0.4)
X = vectorizer.fit_transform(train_df["text"])
print(X)

<Compressed Sparse Row sparse matrix of dtype 'int64'
	with 39134 stored elements and shape (2560, 8856)>
  Coords	Values
  (0, 6578)	1
  (0, 4219)	1
  (0, 2106)	1
  (0, 8000)	2
  (0, 717)	1
  (0, 42)	1
  (0, 1280)	1
  (0, 5260)	1
  (0, 1607)	1
  (0, 7889)	1
  (0, 3630)	1
  (0, 3406)	1
  (0, 4759)	1
  (0, 7345)	1
  (0, 2707)	1
  (0, 3476)	1
  (0, 7883)	1
  (0, 487)	1
  (0, 6769)	1
  (0, 4269)	1
  (0, 1441)	1
  (0, 8405)	1
  (0, 1889)	1
  (0, 5466)	1
  (0, 7461)	1
  :	:
  (2557, 5905)	1
  (2557, 3595)	1
  (2557, 6745)	1
  (2557, 1023)	1
  (2557, 5259)	1
  (2558, 8000)	1
  (2558, 5331)	1
  (2558, 6733)	1
  (2558, 970)	1
  (2558, 4150)	1
  (2558, 874)	1
  (2559, 4219)	1
  (2559, 5128)	1
  (2559, 285)	1
  (2559, 5292)	1
  (2559, 6278)	1
  (2559, 5326)	1
  (2559, 7929)	1
  (2559, 3336)	1
  (2559, 5622)	1
  (2559, 6748)	1
  (2559, 8629)	1
  (2559, 7915)	1
  (2559, 1679)	1
  (2559, 5904)	1


In [5]:
dense_matrix = X.todense()
print(dense_matrix)

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [6]:
print(vectorizer.get_feature_names_out())
print(len(vectorizer.get_feature_names_out()))

['10' '100' '101' ... 'zone' 'ótimo' 'últimos']
8856


In [18]:

print(vectorizer.get_stop_words())

frozenset({'everyone', 'someone', 'see', 'cannot', 'become', 'together', 'whereas', 'bottom', 'them', 'go', 'hers', 'amongst', 'became', 'elsewhere', 'i', 'without', 'noone', 'was', 'same', 'also', 'thus', 'onto', 'what', 'he', 'through', 'these', 'sometimes', 'fifteen', 'almost', 'her', 'other', 'have', 'she', 'mill', 'hence', 'but', 'before', 'by', 'describe', 'moreover', 'next', 'further', 'were', 'two', 'between', 'since', 'once', 'sincere', 'several', 'get', 'and', 'de', 'am', 'throughout', 'itself', 'wherein', 'seemed', 'cant', 'perhaps', 'when', 'very', 'been', 'only', 'cry', 'ten', 'across', 'their', 'nobody', 'be', 'however', 'its', 'neither', 'for', 'un', 'detail', 'third', 'if', 'why', 'with', 'would', 'show', 'those', 'something', 'yet', 'now', 'all', 'none', 'herself', 'being', 'sixty', 'herein', 'nine', 'co', 'thin', 'more', 'every', 'an', 'fill', 'anyone', 'among', 'whenever', 'such', 'done', 'nevertheless', 'ours', 'thence', 'again', 'serious', 'mostly', 'should', 'ever

print(vectorizer.stop_words_) for <1.7 version of scikit learn

print(vectorizer.get_stop_words())  for >1.7 version of scikit learn

In [20]:
first_review = test_df['text'].iat[0]
print(first_review)

lovingly photographed in the manner of a golden book sprung to life , stuart little 2 manages sweetness largely without stickiness .


In [21]:
sparse_vector = vectorizer.transform([first_review])
print(sparse_vector)
dense_vector = sparse_vector.todense()
np.set_printoptions(threshold=sys.maxsize)
print(dense_vector)
np.set_printoptions(threshold=False)

<Compressed Sparse Row sparse matrix of dtype 'int64'
	with 10 stored elements and shape (1, 8592)>
  Coords	Values
  (0, 909)	1
  (0, 4330)	1
  (0, 4437)	1
  (0, 4497)	1
  (0, 4563)	1
  (0, 4653)	1
  (0, 4666)	1
  (0, 5591)	1
  (0, 7347)	1
  (0, 7514)	1
[[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0

In [23]:
vectorizer = CountVectorizer(max_df=300)
X = vectorizer.fit_transform(train_df["text"])
print(vectorizer.get_stop_words())

None


In [24]:
vectorizer = CountVectorizer(stop_words=['the', 'this', 'these', 'in', 'at', 'for'])
X = vectorizer.fit_transform(train_df["text"])

In [25]:
vectorizer = CountVectorizer(max_df=300)
(train_df, test_df) = load_train_test_dataset_pd()
X = vectorizer.fit_transform(train_df["text"])
vectorize = lambda x: vectorizer.transform([x]).toarray()[0]
(X_train, X_test, y_train, y_test) = create_train_test_data(train_df, test_df, vectorize)
clf = train_classifier(X_train, y_train)
test_classifier(test_df, clf)

              precision    recall  f1-score   support

           0       0.74      0.69      0.72       160
           1       0.71      0.76      0.74       160

    accuracy                           0.73       320
   macro avg       0.73      0.73      0.73       320
weighted avg       0.73      0.73      0.73       320

